<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes (iconify MDI)
 * my-2 my-4 my-6 my-8 my-10 my-12 my-14 my-16 my-18 my-20 my-22 my-24
 * md:my-2 md:my-4 md:my-6 md:my-8 md:my-10 md:my-12 md:my-14 md:my-16 md:my-18 md:my-20 md:my-22 md:my-24
 * lg:my-2 lg:my-4 lg:my-6 lg:my-8 lg:my-10 lg:my-12 lg:my-14 lg:my-16 lg:my-18 lg:my-20 lg:my-22 lg:my-24
 * xl:my-2 xl:my-4 xl:my-6 xl:my-8 xl:my-10 xl:my-12 lx:my-14 xl:my-16 xl:my-18 xl:my-20 xl:my-22 xl:my-24
 * 2xl:my-2 2xl:my-4 2xl:my-6 2xl:my-8 2xl:my-10 2xl:my-12 2lx:my-14 2xl:my-16 2xl:my-18 2xl:my-20 2xl:my-22 2xl:my-24
 */


$block_name = 'spacer';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Spacer default classes
$spacer_default_classes = 'not-prose border-b-0';

//
$spacer = $spacer_md = $spacer_lg = $spacer_xl = $spacer_2xl = $spacer_style_classes = '';

//
$root_spacer = 'my-';

if( get_field('spacer') !== 0 && get_field('spacer') !== 'default' ) $spacer = $root_spacer.(get_field('spacer')*2);
if( get_field('spacer_md') !== 'default' ) $spacer_md = 'md:'.$root_spacer.(get_field('spacer_md')*2);
if( get_field('spacer_lg') !== 'default' ) $spacer_lg = 'lg:'.$root_spacer.(get_field('spacer_lg')*2);
if( get_field('spacer_xl') !== 'default' ) $spacer_xl = 'xl:'.$root_spacer.(get_field('spacer_xl')*2);
if( get_field('spacer_2xl') !== 'default' ) $spacer_2xl = '2xl:'.$root_spacer.(get_field('spacer_2xl')*2);

if(get_field('spacer_style') == 'light'){
	$spacer_style_classes = 'border-t border-gray-300';
} elseif(get_field('spacer_style') == 'dark'){
	$spacer_style_classes = 'border-t border-gray-600';
} else{
	$spacer_style_classes = 'border-none';
}

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes,
	$spacer_default_classes,
	$spacer,
	$spacer_md,
	$spacer_lg,
	$spacer_xl,
	$spacer_2xl,
	$spacer_style_classes,
);

$classes = implode( ' ', $all_classes );

?>

<hr class="<?php echo $classes ?>" />
