<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes (iconify MDI)
 * icon-[mdi-light--check] icon-[mdi-light--chevron-right] icon-[mdi-light--chevron-double-right]
 *
 */


$block_name = 'testimonial-slider';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

$slider_default_classes = 'glide relative px-6 sm:px-8 xl:px-12 2xl:px-16';

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$slider_default_classes,
	$additional_classes,
);

$classes = implode( ' ', $all_classes );

// Pass into template part for re-using outside of Block
//get_template_part( 'template-parts/components/badge', null, array('text' => $text, 'classes' => $classes, 'anchor' => $anchor ) );

$i = 1;
?>

<?php if( have_rows('testimonials') ): ?>
	<div <?php echo esc_attr( $anchor ); ?> class="<?php echo $classes ?>">
		<div class="glide__track" data-glide-el="track">
			<div class="glide__slides">
				<?php while( have_rows('testimonials') ) : the_row(); ?>
					<?php if ($is_preview && $i === 1) ?>
					<div class="glide__slide text-center <?php if($is_preview && $i > 1) echo 'hidden' ?>">
						<div class="testimonial-text">
							<?php echo get_sub_field('testimonial_content'); ?>
						</div>
						<span class="block mt-6 text-primary sm:text-lg lg:text-xl uppercase"><?php echo get_sub_field('testimonial_signature'); ?></span>
					</div>
					<?php $i++; ?>
				<?php endwhile; ?>
			</div>
		</div>

		<div class="glide__arrows" data-glide-el="controls">
			<button class="top-1/2 left-0 absolute -translate-y-1/2 glide__arrow glide__arrow--prev" data-glide-dir="<">
				<span class="icon-[mdi--chevron-left] size-8 2xl:size-12 xl:size-10"></span>
			</button>
			<button class="top-1/2 right-0 absolute -translate-y-1/2 glide__arrow glide__arrow--next" data-glide-dir=">">
				<span class="icon-[mdi--chevron-right] size-8 2xl:size-12 xl:size-10"></span>
			</button>
		</div>

	</div>
<?php endif ?>



