<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes (iconify MDI)
 * icon-[mdi-light--check] icon-[mdi-light--chevron-right] icon-[mdi-light--chevron-double-right]
 *
 */


$block_name = 'accordion';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes,
);

$classes = implode( ' ', $all_classes );

// Pass into template part for re-using outside of Block
//get_template_part( 'template-parts/components/badge', null, array('text' => $text, 'classes' => $classes, 'anchor' => $anchor ) );

$i = 1;
?>

<?php if( have_rows('accordion') ): ?>
	<div x-data="{
        active: 'q1',
    	setActive(question) {
      		this.active = (this.active !== question) ? question : '';
    	}
    }" class="relative w-full mx-auto overflow-hidden text-sm font-normal ">
		<?php while( have_rows('accordion') ) : the_row(); ?>



			<details x-bind:open="active === 'q<?php echo $i ?>'" class="group">
				<summary
				x-on:click.prevent="setActive('q<?php echo $i ?>')"
				class="flex cursor-pointer list-none items-center justify-between py-3 [&::-webkit-details-marker]:hidden"
				>
				<h4 class="text-left text-base"><?php echo get_sub_field('accordion_title'); ?></h4>
				<div class="relative size-5 opacity-40">
					<svg
					class="hi-mini hi-chevron-down absolute inline-block size-5 transition duration-150 ease-out group-open:translate-y-4 group-open:opacity-0"
					xmlns="http://www.w3.org/2000/svg"
					viewBox="0 0 20 20"
					fill="currentColor"
					aria-hidden="true"
					>
					<path
						fill-rule="evenodd"
						d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z"
						clip-rule="evenodd"
					/>
					</svg>
					<svg
					xmlns="http://www.w3.org/2000/svg"
					viewBox="0 0 20 20"
					fill="currentColor"
					data-slot="icon"
					class="hi-mini hi-chevron-up absolute inline-block size-5 -translate-y-4 opacity-0 transition duration-150 ease-out group-open:translate-y-0 group-open:opacity-100"
					>
					<path
						fill-rule="evenodd"
						d="M9.47 6.47a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 1 1-1.06 1.06L10 8.06l-3.72 3.72a.75.75 0 0 1-1.06-1.06l4.25-4.25Z"
						clip-rule="evenodd"
					/>
					</svg>
				</div>
				</summary>
				<div class="text-sm">
					<?php echo get_sub_field('accordion_content'); ?>
				</div>
			</details>

			<?php $i++ ?>
		<?php endwhile; ?>
	</div>
<?php endif; ?>
