<?php
/**
 * button Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 */



// Block Name
$block_name = 'button';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Block BG
$background = ( empty( $block['backgroundColor'] ) ) ? '' : 'has-' . $block['backgroundColor'] . '-background-color';

$has_background = $background ? 'has-background' : '';

// BLOCK EDITOR HACK: Use $block['align'] to apply 'text-center' on div wrapper
$align = ( empty( $block['align'] ) ) ? '' : 'align' . $block['align'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Default classes
$default_classes = 'btn group relative';

// Custom border radius
if (str_contains($additional_classes, 'is-style-rounded-md')) {
	$additional_classes = str_replace('is-style-rounded-md', 'rounded-md', $additional_classes);
}
if (str_contains($additional_classes, 'is-style-rounded-full')) {
	$additional_classes = str_replace('is-style-rounded-full', 'rounded-full', $additional_classes);
}
if (str_contains($align, 'aligncenter')) {
	$align = str_replace('aligncenter', 'text-center', $align);
}

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$background,
	$has_background,
	$additional_classes,
	$default_classes,
);

$classes = implode( ' ', $all_classes );
?>

<div <?php echo esc_attr( $anchor ); ?> class="<?php echo $align ?>">
	<?php get_template_part( 'template-parts/components/button', null, array('classes' => $classes) ); ?>
</div>
