<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes
 *
 */


$block_name = 'contact-info';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes,
);

$classes = implode( ' ', $all_classes );

?>
<div class="lg:flex">
	<?php get_template_part( 'template-parts/components/contact-info', null, array('classes' => $classes, 'anchor' => $anchor ) ); ?>
</div>
