<?php
/**
 * grid-row Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * @param   block helper functions: theme/inc/block-helpers.php
 *
 * _tw safelist classes
 * sm:items-start sm:items-center sm:items-end
 * md:items-start md:items-center md:items-end
 * lg:items-start lg:items-center lg:items-end
 * xl:items-start xl:items-center xl:items-end
 * 2xl:items-start 2xl:items-center 2xl:items-end
 * gap-0 gap-2 gap-4 gap-6 gap-8 gap-10 gap-12 gap-14 gap-16 gap-18 gap-20 gap-22 gap-24
 * sm:gap-0 sm:gap-2 sm:gap-4 sm:gap-6 sm:gap-8 sm:gap-10 sm:gap-12 sm:gap-14 sm:gap-16 sm:gap-18 sm:gap-20 sm:gap-22 sm:gap-24
 * md:gap-0 md:gap-2 md:gap-4 md:gap-6 md:gap-8 md:gap-10 md:gap-12 md:gap-14 md:gap-16 md:gap-18 md:gap-20 md:gap-22 md:gap-24
 * lg:gap-0 lg:gap-2 lg:gap-4 lg:gap-6 lg:gap-8 lg:gap-10 lg:gap-12 lg:gap-14 lg:gap-16 lg:gap-18 lg:gap-20 lg:gap-22 lg:gap-24
 * xl:gap-0 xl:gap-2 xl:gap-4 xl:gap-6 xl:gap-8 xl:gap-10 xl:gap-12 xl:gap-14 xl:gap-16 xl:gap-18 xl:gap-20 xl:gap-22 xl:gap-24
 * 2xl:gap-0 2xl:gap-2 2xl:gap-4 2xl:gap-6 2xl:gap-8 2xl:gap-10 2xl:gap-12 2xl:gap-14 2xl:gap-16 2xl:gap-18 2xl:gap-20 2xl:gap-22 2xl:gap-24
 */

$block_name = 'grid-row';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Init
$gap = $gap_sm = $gap_md = $gap_lg = $gap_xl = $gap_2xl = '';
$v_align = $v_align_sm = $v_align_md = $v_align_lg = $v_align_xl = $v_align_2xl = '';
$multiplier = 2;
$grid_columns = 'grid-cols-12';

// Class roots
$root_v_align = 'items-';
$root_gap = 'gap-';

// Default classes
$default_classes = 'grid grid-has-children';

// Get # of grid columns
if(get_field('grid_columns') == 10) $grid_columns = 'grid-cols-10';


if( get_field('vertical_align_sm') !== NULL && get_field('vertical_align_sm') !== 'unset' ) $v_align_sm = 'sm:'.$root_v_align.get_field('vertical_align_sm');
if( get_field('vertical_align_md') !== NULL && get_field('vertical_align_md') !== 'unset') $v_align_md = 'md:'.$root_v_align.get_field('vertical_align_md');
if( get_field('vertical_align_lg') !== NULL && get_field('vertical_align_lg') !== 'unset') $v_align_lg = 'lg:'.$root_v_align.get_field('vertical_align_lg');
if( get_field('vertical_align_xl') !== NULL && get_field('vertical_align_xl') !== 'unset') $v_align_xl = 'xl:'.$root_v_align.get_field('vertical_align_xl');
if( get_field('vertical_align_2xl') !== NULL && get_field('vertical_align_2xl') !== 'unset') $v_align_2xl = '2xl:'.$root_v_align.get_field('vertical_align_2xl');

// $gap = $root_gap.calculateGap(get_field('gap'));
// $gap_sm = 'sm:'.$root_gap.calculateGap(get_field('gap_sm'));
// $gap_md = 'md:'.$root_gap.calculateGap(get_field('gap_md'));
// $gap_lg = 'lg:'.$root_gap.calculateGap(get_field('gap_lg'));
// $gap_xl = 'xl:'.$root_gap.calculateGap(get_field('gap_xl'));
// $gap_2xl = '2xl:'.$root_gap.calculateGap(get_field('gap_2xl'));

if( get_field('gap') !== 0 ) $gap = $root_gap.( get_field('gap')*$multiplier);
if( get_field('gap_sm') !== 0 && get_field('gap_sm') !== 'default' ) $gap_sm = 'sm:'.$root_gap.(get_field('gap_sm')*$multiplier);
if( get_field('gap_md') !== 0 && get_field('gap_md') !== 'default' ) $gap_md = 'md:'.$root_gap.(get_field('gap_md')*$multiplier);
if( get_field('gap_lg') !== 0 && get_field('gap_lg') !== 'default' ) $gap_lg = 'lg:'.$root_gap.(get_field('gap_lg')*$multiplier);
if( get_field('gap_xl') !== 0 && get_field('gap_xl') !== 'default' ) $gap_xl = 'xl:'.$root_gap.(get_field('gap_xl')*$multiplier);
if( get_field('gap_2xl') !== 0 && get_field('gap_2xl') !== 'default' ) $gap_2xl = '2xl:'.$root_gap.(get_field('gap_2xl')*$multiplier);

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$v_align_sm,
	$v_align_md,
	$v_align_lg,
	$v_align_xl,
	$v_align_2xl,
	$gap,
	$gap_sm,
	$gap_md,
	$gap_lg,
	$gap_xl,
	$gap_2xl,
	$grid_columns,
	$default_classes,
	$additional_classes,
);

$classes = implode( ' ', $all_classes );
$classes = trim($classes);
$classes = preg_replace('/\s+/', ' ', $classes);

?>

<div <?php echo esc_attr( $anchor ); ?>>
	<InnerBlocks class="<?php echo $classes ?>" />
</div>
