<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes (iconify MDI)
 * icon-[material-symbols-light--asterisk-rounded]
 * justify-start justify-center justify-end
 */


$block_name = 'accent-icon';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes,
);

$classes = implode( ' ', $all_classes );

//
if( get_field('text') ) $text = get_field('text');
$align = get_field('align') ?: 'justify-start';

// Pass into template part for re-using outside of Block


?>
<div class="asterisk-icon flex <?php echo $align ?>">
	<span class="icon-[material-symbols-light--asterisk-rounded] size-20 lg:size-30 xl:size-40 2xl:size-48 text-foreground"></span>
</div>
