<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes (iconify MDI)
 * icon-[mdi-light--check] icon-[mdi-light--chevron-right] icon-[mdi-light--chevron-double-right]
 *
 */


$block_name = 'styled-title';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

$default_classes = 'styled-title';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$default_classes,
	$additional_classes,
);

$classes = implode( ' ', $all_classes );

//
$text = 'Title Text';
$accent = 'Accent';
$text_2 = 'MoreText';
$trigger_title = get_field('trigger_title') ?: '';
if( get_field('title') ) $text = get_field('title');
if( get_field('accent') ) $accent = get_field('accent');
if( get_field('title_add') ) $text_2 = get_field('title_add');

?>

<div <?php echo esc_attr( $anchor ); ?>  class="<?php echo $classes ?>">
	<div class="flex gap-4 mb-6 2xl:mb-8">
		<div class="pre-style">
			<span class="h4 font-serif italic"><?php echo $text ?></span>
		</div>
		<div class="mt-6">
			<span class="h2 text-primary font-serif italic"><?php echo $accent?></span>
		</div>
		<div class="mt-18 post-style">
			<span class="h4 font-serif italic"><?php echo $text_2 ?></span>
		</div>
	</div>
</div>

