<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist
 * justify-start justify-center justify-end
 *
 */


$block_name = 'magnetic-button';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes,
);

$classes = implode( ' ', $all_classes );


$link = get_field('link') ?: '#';
$link_text = get_field('link_text') ?: 'Learn More';
$align = get_field('align') ?: 'justify-start';
$size = get_field('size') ?: 'default';

?>

<div class="flex <?php echo $align ?>">
	<?php get_template_part( 'template-parts/components/magnetic-button', null, array('link' => $link, 'link_text' => $link_text, 'classes' => $classes, 'size' => $size) ); ?>
</div>


