<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes (iconify MDI)
 * icon-[mdi-light--check] icon-[mdi-light--chevron-right] icon-[mdi-light--chevron-double-right]
 *
 */


$block_name = 'badge';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes,
);

$classes = implode( ' ', $all_classes );

//
$text = 'Badge text...';
if( get_field('text') ) $text = get_field('text');
$align = get_field('align') ?: 'justify-start';

// Pass into template part for re-using outside of Block


?>
<div class="flex <?php echo $align ?>">
	<?php get_template_part( 'template-parts/components/badge', null, array('text' => $text, 'classes' => $classes, 'anchor' => $anchor ) ); ?>
</div>
