<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes (iconify MDI)
 * my-2 my-4 my-6 my-8 my-10 my-12 my-14 my-16 my-18 my-20 my-22 my-24
 * md:my-2 md:my-4 md:my-6 md:my-8 md:my-10 md:my-12 md:my-14 md:my-16 md:my-18 md:my-20 md:my-22 md:my-24
 * lg:my-2 lg:my-4 lg:my-6 lg:my-8 lg:my-10 lg:my-12 lg:my-14 lg:my-16 lg:my-18 lg:my-20 lg:my-22 lg:my-24
 * xl:my-2 xl:my-4 xl:my-6 xl:my-8 xl:my-10 xl:my-12 lx:my-14 xl:my-16 xl:my-18 xl:my-20 xl:my-22 xl:my-24
 * 2xl:my-2 2xl:my-4 2xl:my-6 2xl:my-8 2xl:my-10 2xl:my-12 2lx:my-14 2xl:my-16 2xl:my-18 2xl:my-20 2xl:my-22 2xl:my-24
 * !mb-0
 */


$block_name = 'card';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Card default classes
$card_default_classes = 'content-card overflow-hidden';

if( get_field('style') === 'gray' ){
	$card_styles = 'py-8 px-4 border-2 border-foreground bg-tertiary rounded-[3rem] rounded-tr-none h-full';
} else{
	$card_styles = 'rounded-tl-[3rem]';
}

$icon = get_field('show_icon') ? '<div class="size-20"><div class="absolute card-icon"><span class="icon-[material-symbols-light--asterisk-rounded] size-20"></span></div></div>' : '';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$additional_classes,
	$card_default_classes,
	$card_styles,
);

$classes = implode( ' ', $all_classes );

?>

<div <?php echo esc_attr( $anchor ); ?> class="<?php echo $classes ?>">
	<?php echo $icon ?>
	<InnerBlocks class="space-y-3" />
</div>

