<?php
/**
 * list Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes (iconify MDI)
 * icon-[mdi-light--check] icon-[mdi-light--chevron-right] icon-[mdi-light--chevron-double-right]
 *
 */


$block_name = 'testimonial-slider';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

$slider_default_classes = 'glide';

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$slider_default_classes,
	$additional_classes,
);

$classes = implode( ' ', $all_classes );

// Pass into template part for re-using outside of Block
//get_template_part( 'template-parts/components/badge', null, array('text' => $text, 'classes' => $classes, 'anchor' => $anchor ) );

$i = 1;
?>

<?php if( have_rows('infinite') ): ?>
<div class="overflow-hidden py-4 sm:py-6">
	<div
		x-data="{}"
		x-init="$nextTick(() => {
			let ul = $refs.logos;
			ul.insertAdjacentHTML('afterend', ul.outerHTML);
			ul.nextSibling.setAttribute('aria-hidden', 'true');
		})"
		class="w-full inline-flex flex-nowrap overflow-hidden [mask-image:_linear-gradient(to_right,transparent_0,_white_128px,_white_calc(100%-128px),transparent_100%)]" >

		<ul x-ref="logos" class="!mb-0 flex items-center justify-center md:justify-start [&_li]:mx-5 [&_img]:max-w-15 sm:[&_li]:mx-10 sm:[&_img]:max-w-30 lg:[&_li]:mx-10 lg:[&_img]:max-w-45 xl:[&_li]:mx-14 xl:[&_img]:max-w-55 animate-infinite-scroll">
			<?php while( have_rows('infinite') ) : the_row(); ?>
				<li>
					<?php $img = get_sub_field('img'); ?>
					<img src="<?php echo esc_url($img['url'])?>" alt="<?php echo esc_attr($img['alt']) ?>"/>
				</li>
			<?php endwhile; ?>
			<?php while( have_rows('infinite') ) : the_row(); ?>
				<li>
					<?php $img = get_sub_field('img'); ?>
					<img src="<?php echo esc_url($img['url'])?>" alt="<?php echo esc_attr($img['alt']) ?>"/>
				</li>
			<?php endwhile; ?>
		</ul>

	</div>
</div>
<?php endif; ?>



