<?php
/**
 * grid-col Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 *
 * _tw safelist classes
 * sm:col-span-1 sm:col-span-2 sm:col-span-3 sm:col-span-4 sm:col-span-5 sm:col-span-6
 * sm:col-span-7 sm:col-span-8 sm:col-span-9 sm:col-span-10 sm:col-span-11 sm:col-span-12
 * md:col-span-1 md:col-span-2 md:col-span-3 md:col-span-4 md:col-span-5 md:col-span-6
 * md:col-span-7 md:col-span-8 md:col-span-9 md:col-span-10 md:col-span-11 md:col-span-12
 * lg:col-span-1 lg:col-span-2 lg:col-span-3 lg:col-span-4 lg:col-span-5 lg:col-span-6
 * lg:col-span-7 lg:col-span-8 lg:col-span-9 lg:col-span-10 lg:col-span-11 lg:col-span-12
 * xl:col-span-1 xl:col-span-2 xl:col-span-3 xl:col-span-4 xl:col-span-5 xl:col-span-6
 * xl:col-span-7 xl:col-span-8 xl:col-span-9 xl:col-span-10 xl:col-span-11 xl:col-span-12
 * 2xl:col-span-1 2xl:col-span-2 2xl:col-span-3 2xl:col-span-4 2xl:col-span-5 2xl:col-span-6
 * 2xl:col-span-7 2xl:col-span-8 2xl:col-span-9 2xl:col-span-10 2xl:col-span-11 2xl:col-span-12
 * sm:order-0 sm:order-1 sm:order-2 sm:order-3 sm:order-4 sm:order-5 sm:order-6 sm:order-7 sm:order-8
 * md:order-0 md:order-1 md:order-2 md:order-3 md:order-4 md:order-5 md:order-6 md:order-7 md:order-8
 * lg:order-0 lg:order-1 lg:order-2 lg:order-3 lg:order-4 lg:order-5 lg:order-6 lg:order-7 lg:order-8
 * xl:order-0 xl:order-1 xl:order-2 xl:order-3 xl:order-4 xl:order-5 xl:order-6 xl:order-7 xl:order-8
 * 2xl:order-0 2xl:order-1 2xl:order-2 2xl:order-3 2xl:order-4 2xl:order-5 2xl:order-6 2xl:order-7 2xl:order-8
 * lg:ps-2 lg:ps-4 lg:ps-6 lg:ps-8 lg:ps-10 lg:ps-12
 * xl:ps-2 xl:ps-4 xl:ps-6 xl:ps-8 xl:ps-10 xl:ps-12
 * 2xl:ps-2 2xl:ps-4 2xl:ps-6 2xl:ps-8 2xl:ps-10 2xl:ps-12 2xl:ps-14 2xl:ps-16 2xl:ps-18 2xl:ps-20 2xl:ps-22 2xl:ps-24
 * lg:pe-2 lg:pe-4 lg:pe-6 lg:pe-8 lg:pe-10 lg:pe-12
 * xl:pe-2 xl:pe-4 xl:pe-6 xl:pe-8 xl:pe-10 xl:pe-12
 * 2xl:pe-2 2xl:pe-4 2xl:pe-6 2xl:pe-8 2xl:pe-10 2xl:pe-12 2xl:pe-14 2xl:pe-16 2xl:pe-18 2xl:pe-20 2xl:pe-22 2xl:pe-24
 */

$block_name = 'grid-col';

$namespace = 'acf';

$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// Block #id
$anchor = ( empty( $block['anchor'] ) ) ? null : 'id=' . $block['anchor'];

// Additional editor classes including $block['style'] defined in block.json
$additional_classes = $block['className'] ?? '';

// Init
$col_width = $col_width_sm = $col_width_md = $col_width_lg = $col_width_xl = $col_width_2xl = '';
$order = $order_sm = $order_md = $order_lg = $order_xl = $order_2xl = '';
$all_spacing_classes = [];
$ps = $ps_lg = $ps_xl = $ps_2xl = '';
$pe = $pe_lg = $pe_xl = $pe_2xl = '';

$col_width = 'col-span-12';

// Set class roots
$root_width = 'col-span-';
$root_order = 'order-';
$root_ps = 'ps-';
$root_pe = 'pe-';

if( ( get_field('width_sm') && get_field('width_sm') != 0 ) ) $col_width_sm = 'sm:'.$root_width.get_field('width_sm');
if( ( get_field('width_md') && get_field('width_md') != 0 ) ) $col_width_md = 'md:'.$root_width.get_field('width_md');
if( ( get_field('width_lg') && get_field('width_lg') != 0 ) ) $col_width_lg = 'lg:'.$root_width.get_field('width_lg');
if( ( get_field('width_xl') && get_field('width_xl') != 0 ) ) $col_width_xl = 'xl:'.$root_width.get_field('width_xl');
if( ( get_field('width_2xl') && get_field('width_2xl') != 0 ) ) $col_width_2xl = '2xl:'.$root_width.get_field('width_2xl');

if( get_field('order_sm') !== NULL && get_field('order_sm') !== 'default' ) $order_sm = 'sm:'.$root_order.get_field('order_sm');
if( get_field('order_md') !== NULL && get_field('order_md') !== 'default' ) $order_md = 'md:'.$root_order.get_field('order_md');
if( get_field('order_lg') !== NULL && get_field('order_lg') !== 'default' ) $order_lg = 'lg:'.$root_order.get_field('order_lg');
if( get_field('order_xl') !== NULL && get_field('order_xl') !== 'default' ) $order_xl = 'xl:'.$root_order.get_field('order_xl');
if( get_field('order_2xl') !== NULL && get_field('order_2xl') !== 'default' ) $order_2xl = '2xl:'.$root_order.get_field('order_2xl');

if( have_rows('spacing_lg') ){
	while( have_rows('spacing_lg') ): the_row();
		if( get_sub_field('ps') != 0 ) $ps_lg = 'lg:'.$root_ps.(get_sub_field('ps')*2);
		if( get_sub_field('pe') != 0 ) $pe_lg = 'lg:'.$root_pe.(get_sub_field('pe')*2);
	endwhile;
}
if( get_field('show_spacing_lg') ) array_push($all_spacing_classes, $ps_lg, $pe_lg);

if( have_rows('spacing_xl') ){
	while( have_rows('spacing_xl') ): the_row();
		if( get_sub_field('ps') != 0 ) $ps_xl = 'xl:'.($root_ps.get_sub_field('ps')*2);
		if( get_sub_field('pe') != 0 ) $pe_xl = 'xl:'.($root_pe.get_sub_field('pe')*2);
	endwhile;
}
if( get_field('show_spacing_xl') ) array_push($all_spacing_classes, $ps_xl, $pe_xl);

if( have_rows('spacing_2xl') ){
	while( have_rows('spacing_2xl') ): the_row();
		if( get_sub_field('ps') != 0 ) $ps_2xl = '2xl:'.($root_ps.get_sub_field('ps')*2);
		if( get_sub_field('pe') != 0 ) $pe_2xl = '2xl:'.($root_pe.get_sub_field('pe')*2);
	endwhile;
}
if( get_field('show_spacing_2xl') ) array_push($all_spacing_classes, $ps_2xl, $pe_2xl);


$spacing_classes = implode( ' ', $all_spacing_classes );

// Create array $all_classes and implode
$all_classes = array(
	$block_name,
	$col_width,
	$col_width_sm,
	$col_width_md,
	$col_width_lg,
	$col_width_xl,
	$col_width_2xl,
	$order_sm,
	$order_md,
	$order_lg,
	$order_xl,
	$order_2xl,
	$spacing_classes,
	$additional_classes,
);

$classes = implode( ' ', $all_classes );
$classes = trim($classes);
$classes = preg_replace('/\s+/', ' ', $classes);
?>

<div <?php echo esc_attr( $anchor ); ?> class="<?php echo $classes; ?>">
	<InnerBlocks class="grid-column-inner h-full"/>
</div>

